#!/bin/bash

printwindow() {
    input=$(echo $event | grep -oP '(?<=activewindow>>)[^ ].*' | sed -E 's/( - | — )[^—]*$//')

    if [[ ! -z "$input" ]]; then
        echo $input
    fi
}

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do
printwindow $event
done
